"""update box table

Revision ID: 6a5c7d939dfc
Revises: 1adbb75050b1
Create Date: 2025-10-20 19:58:28.922489

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6a5c7d939dfc"
down_revision: Union[str, Sequence[str], None] = "1adbb75050b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("boxes", sa.Column("box_id", sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f("uq_boxes_box_id"), "boxes", ["box_id"])
    op.create_foreign_key(
        op.f("fk_boxes_box_id_boxes"),
        "boxes",
        "boxes",
        ["box_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_boxes_box_id_boxes"), "boxes", type_="foreignkey"
    )
    op.drop_constraint(op.f("uq_boxes_box_id"), "boxes", type_="unique")
    op.drop_column("boxes", "box_id")
    # ### end Alembic commands ###
